import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import * as Icons from 'griddy-icons';
import { writeFileSync } from 'fs';

const needed = {
    // nav
    Home: { regular: true, filled: true },
    AnnotationDots: { regular: true, filled: true },
    Notification: { regular: true, filled: true },
    NotificationRinging: { regular: true },
    User: { regular: true, filled: true },
    Settings: { regular: true },
    LogOut: { regular: true },
    Search: { regular: true },
    // post actions
    Heart: { regular: true, filled: true },
    Annotation: { regular: true },
    Bookmark: { regular: true, filled: true },
    Trash: { regular: true },
    // messaging
    Send: { regular: true },
    ChevronLeft: { regular: true },
    ChevronRight: { regular: true },
    X: { regular: true },
    Close: { regular: true },
    // create / upload
    Plus: { regular: true },
    PlusCircle: { regular: true },
    Image: { regular: true },
    PhotoCamera: { regular: true },
    // follow
    UserPlus: { regular: true },
    UserCheck: { regular: true },
    UserMinus: { regular: true },
    Users: { regular: true },
    // misc
    MoreHorizontal: { regular: true },
    DotsHorizontal: { regular: true },
};

const map = {};

for (const [name, variants] of Object.entries(needed)) {
    const Icon = Icons[name];
    if (!Icon) {
        console.warn(`⚠️  Icon not found: ${name}`);
        continue;
    }
    if (variants.regular) {
        try {
            map[name] = renderToStaticMarkup(createElement(Icon, { size: 20, filled: false }));
        } catch (e) {
            console.warn(`⚠️  Failed regular ${name}:`, e.message);
        }
    }
    if (variants.filled) {
        try {
            map[`${name}Filled`] = renderToStaticMarkup(createElement(Icon, { size: 20, filled: true }));
        } catch (e) {
            console.warn(`⚠️  Failed filled ${name}:`, e.message);
        }
    }
}

const code = `// Auto-generated by scripts/generate-icons.mjs — do not edit manually
export const icons = ${JSON.stringify(map, null, 2)};

export function getIcon(name, size = 20, filled = false) {
    const key = filled ? name + 'Filled' : name;
    const svg = icons[key] || icons[name] || '';
    if (!svg || size === 20) return svg;
    // Swap the default size=20 with the requested size
    return svg.replace(/width="20" height="20"/, \`width="\${size}" height="\${size}"\`);
}
`;

writeFileSync('resources/js/utils/icons-data.js', code);
console.log(`✅  Generated ${Object.keys(map).length} icons → resources/js/utils/icons-data.js`);
